{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os  \n",
    "import sys  \n",
    "import zipfile  \n",
    "import tempfile  \n",
    "import shutil  \n",
    "from tqdm.notebook import tqdm  \n",
    "from dotenv import load_dotenv  \n",
    "\n",
    "# 프로젝트 루트 경로 설정  \n",
    "#sys.path.append('./src')  \n",
    "\n",
    "\n",
    "from update_objectfile import upload_file_with_metadata  \n",
    "from data_engineering.obj_storage.boto3 import MinIOClient  \n",
    "from data_engineering.db.connector import Database  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 환경 변수 로드  \n",
    "load_dotenv('.env')  \n",
    "\n",
    "# MinIO 클라이언트 초기화  \n",
    "minio_client = MinIOClient()  \n",
    "\n",
    "# 데이터셋 경로 설정 (상대 경로 사용)  \n",
    "DATASET_PATH = \"../../DataSet\"  \n",
    "\n",
    "# 처리할 디렉토리 구조  \n",
    "DIRECTORIES = [  \n",
    "    \"Training/01.원천데이터\",  \n",
    "    \"Training/02.라벨링데이터\",  \n",
    "    \"Validation/01.원천데이터\",  \n",
    "    \"Validation/02.라벨링데이터\"  \n",
    "]  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 버킷 이름 설정  \n",
    "BUCKET_NAME = \"tada\"  \n",
    "\n",
    "# 지원하는 이미지 확장자  \n",
    "IMAGE_EXTENSIONS = {\".jpg\", \".jpeg\", \".png\", \".gif\", \".bmp\"}  \n",
    "\n",
    "def is_image_file(filename):  \n",
    "    return any(filename.lower().endswith(ext) for ext in IMAGE_EXTENSIONS)  \n",
    "\n",
    "def get_uploaded_files():  \n",
    "    \"\"\"DB에서 이미 업로드된 파일 목록 가져오기\"\"\"  \n",
    "    db = Database(  \n",
    "        host=os.getenv('DB_HOST'),  \n",
    "        port=int(os.getenv('DB_PORT')),  \n",
    "        user=os.getenv('DB_USER'),  \n",
    "        password=os.getenv('DB_PASSWORD'),  \n",
    "        database=os.getenv('DB_NAME')  \n",
    "    )  \n",
    "    \n",
    "    query = \"SELECT category, object_path FROM object_storage\"  \n",
    "    results = db.getter(query)  \n",
    "    return {(record['category'], record['object_path']) for record in results}  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "object_storage 테이블이 성공적으로 생성되었습니다.\n",
      "이미 업로드된 파일 수: 13838\n",
      "임시 디렉토리 생성됨: C:\\Users\\dongr\\AppData\\Local\\Temp\\tmpc16pon_w\n",
      "\n",
      "처리 중인 디렉토리: Training/01.원천데이터\n",
      "발견된 ZIP 파일 수: 8\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "2e904a411b78403db57a13a7053a4a80",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "ZIP 파일 처리 중:   0%|          | 0/8 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "b5e26b7b67b64d8cbbb144af3d2c4dad",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "파일 추출 중:   0%|          | 0/6058 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Upload error: Read timeout on endpoint URL: \"http://175.214.62.133:50008/tada/Training/01.%EC%9B%90%EC%B2%9C%EB%8D%B0%EC%9D%B4%ED%84%B0/TS_OBJ_1/APT_FP_OBJ_037344144.PNG?uploadId=ZDY0N2RlZjMtYWRlMi00MWY1LThkMWUtZmQ5YjA5NTE5ZTE4LmZkMDIxODhlLWM3NmEtNDE2YS04MWViLWZjYjBlMTE0NjFjY3gxNzMyNTQ2OTg1OTg2ODc5MTA3\"\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_1/APT_FP_OBJ_037344144.PNG\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "1aaf81c8bc8e45efba37b0a9adc28631",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "파일 추출 중:   0%|          | 0/2041 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada/Training/01.%EC%9B%90%EC%B2%9C%EB%8D%B0%EC%9D%B4%ED%84%B0/TS_OBJ_2/APT_FP_OBJ_985691754.PNG?uploadId=ZDY0N2RlZjMtYWRlMi00MWY1LThkMWUtZmQ5YjA5NTE5ZTE4LjUzOTAwOTJjLTMyOTEtNGEwMC1hMDE3LTNiMWZkYzQ0OTBlNngxNzMyNTYyNjk0MjUzMDYwNzgy&partNumber=1\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_985691754.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_983508955.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_983560055.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_983848789.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_988329155.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_986442407.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_992759706.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_984379454.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_986156985.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_997356667.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_986502948.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_985084113.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_985557682.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_985322309.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_987002911.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_985105368.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_987292263.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_985534584.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_990954189.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_993133727.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_036935206.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_986379347.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_986376808.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_989190063.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_986742302.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_986452402.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_987024025.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_991528548.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_989920172.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_987483235.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_994505402.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_992501533.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_987517283.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_987746936.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_988300881.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_990864369.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_988283169.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_988325458.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_994018042.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_018200019.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_992352257.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_989332943.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_989671446.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_994983478.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_989805888.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_992668919.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_997579028.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_990356407.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_990895227.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_993533889.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_013149685.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_993184656.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_990452319.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_992038465.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_991420334.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_993442651.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_991066732.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_992208361.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_992447072.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_997007878.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_994269949.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_992530714.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_992677418.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_995354414.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_995276975.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_997171531.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_995360858.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_993285541.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_999143702.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_995572349.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_996530215.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_994043266.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_994258187.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_994890487.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_012517189.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_996615188.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_994943513.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_025582597.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_995080023.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_995325841.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_997104851.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_059735413.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_995532355.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_083066974.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_995615273.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_996484939.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_995556668.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_996533864.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_005398721.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_999098385.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_996707803.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_022090464.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_996916023.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_996732021.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_997085801.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_999791325.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_997181195.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_997158219.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_997304676.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_999427255.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_997274753.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_999864474.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_019840383.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_997199528.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_998458678.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_008695512.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_998577397.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_998054415.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_999211166.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_999403215.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_009177183.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_035987417.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_999244946.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_999233003.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_002113503.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/APT_FP_OBJ_999593321.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_124652462.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_021847035.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_002529769.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_023477578.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_076371674.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_005626753.png\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_169058781.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_007522916.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_030977947.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_013140654.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_119508149.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_016429172.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_016627671.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_016967479.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_039752094.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_039708797.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_072181072.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_020641977.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_094404017.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_050948229.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_021944873.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_059430222.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_022617714.png\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_050412807.png\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_083166202.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_033246202.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_033789662.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_063782436.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_224033423.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_039732371.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_042386818.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_045172828.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_044785298.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_072965264.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_053964112.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_092045499.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_071144364.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_058566301.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_077019735.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_059342951.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_103480959.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_061656479.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_062330831.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_172716612.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_084884359.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_062893528.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_064523805.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_065137701.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_068700647.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_090634529.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_122916509.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_097772326.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_102948201.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_076807431.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_134021512.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_082007722.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_189117924.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_083696198.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_126604191.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_086135494.PNG\n",
      "Upload error: Connection was closed before we received a valid response from endpoint URL: \"http://175.214.62.133:50008/tada\".\n",
      "업로드 실패: Training/01.원천데이터/TS_OBJ_2/DEH_FP_OBJ_106630541.PNG\n",
      "임시 디렉토리 정리 완료\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mConnectionResetError\u001b[0m                      Traceback (most recent call last)",
      "File \u001b[1;32mc:\\ProgramData\\anaconda3\\Lib\\http\\client.py:1428\u001b[0m, in \u001b[0;36mHTTPConnection.getresponse\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m   1427\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m-> 1428\u001b[0m     response\u001b[38;5;241m.\u001b[39mbegin()\n\u001b[0;32m   1429\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mConnectionError\u001b[39;00m:\n",
      "File \u001b[1;32mc:\\ProgramData\\anaconda3\\Lib\\http\\client.py:331\u001b[0m, in \u001b[0;36mHTTPResponse.begin\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    330\u001b[0m \u001b[38;5;28;01mwhile\u001b[39;00m \u001b[38;5;28;01mTrue\u001b[39;00m:\n\u001b[1;32m--> 331\u001b[0m     version, status, reason \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_read_status()\n\u001b[0;32m    332\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m status \u001b[38;5;241m!=\u001b[39m CONTINUE:\n",
      "File \u001b[1;32mc:\\ProgramData\\anaconda3\\Lib\\http\\client.py:292\u001b[0m, in \u001b[0;36mHTTPResponse._read_status\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    291\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_read_status\u001b[39m(\u001b[38;5;28mself\u001b[39m):\n\u001b[1;32m--> 292\u001b[0m     line \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mstr\u001b[39m(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mfp\u001b[38;5;241m.\u001b[39mreadline(_MAXLINE \u001b[38;5;241m+\u001b[39m \u001b[38;5;241m1\u001b[39m), \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124miso-8859-1\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m    293\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mlen\u001b[39m(line) \u001b[38;5;241m>\u001b[39m _MAXLINE:\n",
      "File \u001b[1;32mc:\\ProgramData\\anaconda3\\Lib\\socket.py:720\u001b[0m, in \u001b[0;36mSocketIO.readinto\u001b[1;34m(self, b)\u001b[0m\n\u001b[0;32m    719\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 720\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_sock\u001b[38;5;241m.\u001b[39mrecv_into(b)\n\u001b[0;32m    721\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m timeout:\n",
      "\u001b[1;31mConnectionResetError\u001b[0m: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[7], line 44\u001b[0m\n\u001b[0;32m     40\u001b[0m     shutil\u001b[38;5;241m.\u001b[39mcopyfileobj(source, target)  \n\u001b[0;32m     42\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:  \n\u001b[0;32m     43\u001b[0m     \u001b[38;5;66;03m# MinIO 업로드 및 메타데이터 저장  \u001b[39;00m\n\u001b[1;32m---> 44\u001b[0m     success \u001b[38;5;241m=\u001b[39m upload_file_with_metadata(  \n\u001b[0;32m     45\u001b[0m         local_path\u001b[38;5;241m=\u001b[39mtemp_path,  \n\u001b[0;32m     46\u001b[0m         category\u001b[38;5;241m=\u001b[39mcategory,  \n\u001b[0;32m     47\u001b[0m         bucket\u001b[38;5;241m=\u001b[39mBUCKET_NAME,  \n\u001b[0;32m     48\u001b[0m         object_path\u001b[38;5;241m=\u001b[39mobject_key  \n\u001b[0;32m     49\u001b[0m     )  \n\u001b[0;32m     50\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m success:  \n\u001b[0;32m     51\u001b[0m         \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m업로드 실패: \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mobject_key\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m)  \n",
      "File \u001b[1;32mg:\\Dropbox\\OssmMath\\52_AI-Project\\TADA\\src\\update_objectfile.py:21\u001b[0m, in \u001b[0;36mupload_file_with_metadata\u001b[1;34m(local_path, category, bucket, object_path)\u001b[0m\n\u001b[0;32m     18\u001b[0m     object_path \u001b[38;5;241m=\u001b[39m os\u001b[38;5;241m.\u001b[39mpath\u001b[38;5;241m.\u001b[39mbasename(local_path)  \n\u001b[0;32m     20\u001b[0m \u001b[38;5;66;03m# 파일 업로드  \u001b[39;00m\n\u001b[1;32m---> 21\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m minio_client\u001b[38;5;241m.\u001b[39mupload_file(local_path, bucket, object_path):  \n\u001b[0;32m     22\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mFalse\u001b[39;00m  \n\u001b[0;32m     24\u001b[0m \u001b[38;5;66;03m# DB 연결 (싱글톤)  \u001b[39;00m\n\u001b[0;32m     25\u001b[0m \u001b[38;5;66;03m#load_dotenv()  \u001b[39;00m\n",
      "File \u001b[1;32mg:\\Dropbox\\OssmMath\\52_AI-Project\\TADA\\src\\data_engineering\\obj_storage\\boto3.py:64\u001b[0m, in \u001b[0;36mMinIOClient.upload_file\u001b[1;34m(self, local_path, bucket, object_path)\u001b[0m\n\u001b[0;32m     62\u001b[0m \u001b[38;5;250m\u001b[39m\u001b[38;5;124;03m\"\"\"파일 업로드\"\"\"\u001b[39;00m  \n\u001b[0;32m     63\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:  \n\u001b[1;32m---> 64\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mensure_bucket_exists(bucket):  \n\u001b[0;32m     65\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m버킷 \u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mbucket\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m 생성/확인 실패\u001b[39m\u001b[38;5;124m\"\u001b[39m)  \n\u001b[0;32m     67\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mclient\u001b[38;5;241m.\u001b[39mupload_file(local_path, bucket, object_path)  \n",
      "File \u001b[1;32mg:\\Dropbox\\OssmMath\\52_AI-Project\\TADA\\src\\data_engineering\\obj_storage\\boto3.py:57\u001b[0m, in \u001b[0;36mMinIOClient.ensure_bucket_exists\u001b[1;34m(self, bucket_name)\u001b[0m\n\u001b[0;32m     55\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mensure_bucket_exists\u001b[39m(\u001b[38;5;28mself\u001b[39m, bucket_name: \u001b[38;5;28mstr\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28mbool\u001b[39m:  \n\u001b[0;32m     56\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"버킷이 없으면 생성\"\"\"\u001b[39;00m  \n\u001b[1;32m---> 57\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mcheck_bucket_exists(bucket_name):  \n\u001b[0;32m     58\u001b[0m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mcreate_bucket(bucket_name)  \n\u001b[0;32m     59\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mTrue\u001b[39;00m\n",
      "File \u001b[1;32mg:\\Dropbox\\OssmMath\\52_AI-Project\\TADA\\src\\data_engineering\\obj_storage\\boto3.py:41\u001b[0m, in \u001b[0;36mMinIOClient.check_bucket_exists\u001b[1;34m(self, bucket_name)\u001b[0m\n\u001b[0;32m     39\u001b[0m \u001b[38;5;250m\u001b[39m\u001b[38;5;124;03m\"\"\"버킷 존재 여부 확인\"\"\"\u001b[39;00m  \n\u001b[0;32m     40\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:  \n\u001b[1;32m---> 41\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mclient\u001b[38;5;241m.\u001b[39mhead_bucket(Bucket\u001b[38;5;241m=\u001b[39mbucket_name)  \n\u001b[0;32m     42\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mTrue\u001b[39;00m  \n\u001b[0;32m     43\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m ClientError:  \n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python312\\site-packages\\botocore\\client.py:569\u001b[0m, in \u001b[0;36mClientCreator._create_api_method.<locals>._api_call\u001b[1;34m(self, *args, **kwargs)\u001b[0m\n\u001b[0;32m    565\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m(\n\u001b[0;32m    566\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mpy_operation_name\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m() only accepts keyword arguments.\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    567\u001b[0m     )\n\u001b[0;32m    568\u001b[0m \u001b[38;5;66;03m# The \"self\" in this scope is referring to the BaseClient.\u001b[39;00m\n\u001b[1;32m--> 569\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_make_api_call(operation_name, kwargs)\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python312\\site-packages\\botocore\\client.py:1005\u001b[0m, in \u001b[0;36mBaseClient._make_api_call\u001b[1;34m(self, operation_name, api_params)\u001b[0m\n\u001b[0;32m   1001\u001b[0m     maybe_compress_request(\n\u001b[0;32m   1002\u001b[0m         \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mmeta\u001b[38;5;241m.\u001b[39mconfig, request_dict, operation_model\n\u001b[0;32m   1003\u001b[0m     )\n\u001b[0;32m   1004\u001b[0m     apply_request_checksum(request_dict)\n\u001b[1;32m-> 1005\u001b[0m     http, parsed_response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_make_request(\n\u001b[0;32m   1006\u001b[0m         operation_model, request_dict, request_context\n\u001b[0;32m   1007\u001b[0m     )\n\u001b[0;32m   1009\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mmeta\u001b[38;5;241m.\u001b[39mevents\u001b[38;5;241m.\u001b[39memit(\n\u001b[0;32m   1010\u001b[0m     \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mafter-call.\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mservice_id\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m.\u001b[39m\u001b[38;5;132;01m{\u001b[39;00moperation_name\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m'\u001b[39m,\n\u001b[0;32m   1011\u001b[0m     http_response\u001b[38;5;241m=\u001b[39mhttp,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   1014\u001b[0m     context\u001b[38;5;241m=\u001b[39mrequest_context,\n\u001b[0;32m   1015\u001b[0m )\n\u001b[0;32m   1017\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m http\u001b[38;5;241m.\u001b[39mstatus_code \u001b[38;5;241m>\u001b[39m\u001b[38;5;241m=\u001b[39m \u001b[38;5;241m300\u001b[39m:\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python312\\site-packages\\botocore\\client.py:1029\u001b[0m, in \u001b[0;36mBaseClient._make_request\u001b[1;34m(self, operation_model, request_dict, request_context)\u001b[0m\n\u001b[0;32m   1027\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_make_request\u001b[39m(\u001b[38;5;28mself\u001b[39m, operation_model, request_dict, request_context):\n\u001b[0;32m   1028\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m-> 1029\u001b[0m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_endpoint\u001b[38;5;241m.\u001b[39mmake_request(operation_model, request_dict)\n\u001b[0;32m   1030\u001b[0m     \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[0;32m   1031\u001b[0m         \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mmeta\u001b[38;5;241m.\u001b[39mevents\u001b[38;5;241m.\u001b[39memit(\n\u001b[0;32m   1032\u001b[0m             \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mafter-call-error.\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_service_model\u001b[38;5;241m.\u001b[39mservice_id\u001b[38;5;241m.\u001b[39mhyphenize()\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m.\u001b[39m\u001b[38;5;132;01m{\u001b[39;00moperation_model\u001b[38;5;241m.\u001b[39mname\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m'\u001b[39m,\n\u001b[0;32m   1033\u001b[0m             exception\u001b[38;5;241m=\u001b[39me,\n\u001b[0;32m   1034\u001b[0m             context\u001b[38;5;241m=\u001b[39mrequest_context,\n\u001b[0;32m   1035\u001b[0m         )\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python312\\site-packages\\botocore\\endpoint.py:119\u001b[0m, in \u001b[0;36mEndpoint.make_request\u001b[1;34m(self, operation_model, request_dict)\u001b[0m\n\u001b[0;32m    113\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mmake_request\u001b[39m(\u001b[38;5;28mself\u001b[39m, operation_model, request_dict):\n\u001b[0;32m    114\u001b[0m     logger\u001b[38;5;241m.\u001b[39mdebug(\n\u001b[0;32m    115\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mMaking request for \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m with params: \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m\"\u001b[39m,\n\u001b[0;32m    116\u001b[0m         operation_model,\n\u001b[0;32m    117\u001b[0m         request_dict,\n\u001b[0;32m    118\u001b[0m     )\n\u001b[1;32m--> 119\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_send_request(request_dict, operation_model)\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python312\\site-packages\\botocore\\endpoint.py:216\u001b[0m, in \u001b[0;36mEndpoint._send_request\u001b[1;34m(self, request_dict, operation_model)\u001b[0m\n\u001b[0;32m    214\u001b[0m     \u001b[38;5;66;03m# Create a new request when retried (including a new signature).\u001b[39;00m\n\u001b[0;32m    215\u001b[0m     request \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mcreate_request(request_dict, operation_model)\n\u001b[1;32m--> 216\u001b[0m     success_response, exception \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_get_response(\n\u001b[0;32m    217\u001b[0m         request, operation_model, context\n\u001b[0;32m    218\u001b[0m     )\n\u001b[0;32m    219\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m (\n\u001b[0;32m    220\u001b[0m     success_response \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[0;32m    221\u001b[0m     \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mResponseMetadata\u001b[39m\u001b[38;5;124m'\u001b[39m \u001b[38;5;129;01min\u001b[39;00m success_response[\u001b[38;5;241m1\u001b[39m]\n\u001b[0;32m    222\u001b[0m ):\n\u001b[0;32m    223\u001b[0m     \u001b[38;5;66;03m# We want to share num retries, not num attempts.\u001b[39;00m\n\u001b[0;32m    224\u001b[0m     total_retries \u001b[38;5;241m=\u001b[39m attempts \u001b[38;5;241m-\u001b[39m \u001b[38;5;241m1\u001b[39m\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python312\\site-packages\\botocore\\endpoint.py:239\u001b[0m, in \u001b[0;36mEndpoint._get_response\u001b[1;34m(self, request, operation_model, context)\u001b[0m\n\u001b[0;32m    233\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_get_response\u001b[39m(\u001b[38;5;28mself\u001b[39m, request, operation_model, context):\n\u001b[0;32m    234\u001b[0m     \u001b[38;5;66;03m# This will return a tuple of (success_response, exception)\u001b[39;00m\n\u001b[0;32m    235\u001b[0m     \u001b[38;5;66;03m# and success_response is itself a tuple of\u001b[39;00m\n\u001b[0;32m    236\u001b[0m     \u001b[38;5;66;03m# (http_response, parsed_dict).\u001b[39;00m\n\u001b[0;32m    237\u001b[0m     \u001b[38;5;66;03m# If an exception occurs then the success_response is None.\u001b[39;00m\n\u001b[0;32m    238\u001b[0m     \u001b[38;5;66;03m# If no exception occurs then exception is None.\u001b[39;00m\n\u001b[1;32m--> 239\u001b[0m     success_response, exception \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_do_get_response(\n\u001b[0;32m    240\u001b[0m         request, operation_model, context\n\u001b[0;32m    241\u001b[0m     )\n\u001b[0;32m    242\u001b[0m     kwargs_to_emit \u001b[38;5;241m=\u001b[39m {\n\u001b[0;32m    243\u001b[0m         \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mresponse_dict\u001b[39m\u001b[38;5;124m'\u001b[39m: \u001b[38;5;28;01mNone\u001b[39;00m,\n\u001b[0;32m    244\u001b[0m         \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mparsed_response\u001b[39m\u001b[38;5;124m'\u001b[39m: \u001b[38;5;28;01mNone\u001b[39;00m,\n\u001b[0;32m    245\u001b[0m         \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mcontext\u001b[39m\u001b[38;5;124m'\u001b[39m: context,\n\u001b[0;32m    246\u001b[0m         \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mexception\u001b[39m\u001b[38;5;124m'\u001b[39m: exception,\n\u001b[0;32m    247\u001b[0m     }\n\u001b[0;32m    248\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m success_response \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python312\\site-packages\\botocore\\endpoint.py:279\u001b[0m, in \u001b[0;36mEndpoint._do_get_response\u001b[1;34m(self, request, operation_model, context)\u001b[0m\n\u001b[0;32m    277\u001b[0m     http_response \u001b[38;5;241m=\u001b[39m first_non_none_response(responses)\n\u001b[0;32m    278\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m http_response \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m--> 279\u001b[0m         http_response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_send(request)\n\u001b[0;32m    280\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m HTTPClientError \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[0;32m    281\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m (\u001b[38;5;28;01mNone\u001b[39;00m, e)\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python312\\site-packages\\botocore\\endpoint.py:383\u001b[0m, in \u001b[0;36mEndpoint._send\u001b[1;34m(self, request)\u001b[0m\n\u001b[0;32m    382\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_send\u001b[39m(\u001b[38;5;28mself\u001b[39m, request):\n\u001b[1;32m--> 383\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mhttp_session\u001b[38;5;241m.\u001b[39msend(request)\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python312\\site-packages\\botocore\\httpsession.py:464\u001b[0m, in \u001b[0;36mURLLib3Session.send\u001b[1;34m(self, request)\u001b[0m\n\u001b[0;32m    461\u001b[0m     conn\u001b[38;5;241m.\u001b[39mproxy_headers[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mhost\u001b[39m\u001b[38;5;124m'\u001b[39m] \u001b[38;5;241m=\u001b[39m host\n\u001b[0;32m    463\u001b[0m request_target \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_get_request_target(request\u001b[38;5;241m.\u001b[39murl, proxy_url)\n\u001b[1;32m--> 464\u001b[0m urllib_response \u001b[38;5;241m=\u001b[39m conn\u001b[38;5;241m.\u001b[39murlopen(\n\u001b[0;32m    465\u001b[0m     method\u001b[38;5;241m=\u001b[39mrequest\u001b[38;5;241m.\u001b[39mmethod,\n\u001b[0;32m    466\u001b[0m     url\u001b[38;5;241m=\u001b[39mrequest_target,\n\u001b[0;32m    467\u001b[0m     body\u001b[38;5;241m=\u001b[39mrequest\u001b[38;5;241m.\u001b[39mbody,\n\u001b[0;32m    468\u001b[0m     headers\u001b[38;5;241m=\u001b[39mrequest\u001b[38;5;241m.\u001b[39mheaders,\n\u001b[0;32m    469\u001b[0m     retries\u001b[38;5;241m=\u001b[39mRetry(\u001b[38;5;28;01mFalse\u001b[39;00m),\n\u001b[0;32m    470\u001b[0m     assert_same_host\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mFalse\u001b[39;00m,\n\u001b[0;32m    471\u001b[0m     preload_content\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mFalse\u001b[39;00m,\n\u001b[0;32m    472\u001b[0m     decode_content\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mFalse\u001b[39;00m,\n\u001b[0;32m    473\u001b[0m     chunked\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_chunked(request\u001b[38;5;241m.\u001b[39mheaders),\n\u001b[0;32m    474\u001b[0m )\n\u001b[0;32m    476\u001b[0m http_response \u001b[38;5;241m=\u001b[39m botocore\u001b[38;5;241m.\u001b[39mawsrequest\u001b[38;5;241m.\u001b[39mAWSResponse(\n\u001b[0;32m    477\u001b[0m     request\u001b[38;5;241m.\u001b[39murl,\n\u001b[0;32m    478\u001b[0m     urllib_response\u001b[38;5;241m.\u001b[39mstatus,\n\u001b[0;32m    479\u001b[0m     urllib_response\u001b[38;5;241m.\u001b[39mheaders,\n\u001b[0;32m    480\u001b[0m     urllib_response,\n\u001b[0;32m    481\u001b[0m )\n\u001b[0;32m    483\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m request\u001b[38;5;241m.\u001b[39mstream_output:\n\u001b[0;32m    484\u001b[0m     \u001b[38;5;66;03m# Cause the raw stream to be exhausted immediately. We do it\u001b[39;00m\n\u001b[0;32m    485\u001b[0m     \u001b[38;5;66;03m# this way instead of using preload_content because\u001b[39;00m\n\u001b[0;32m    486\u001b[0m     \u001b[38;5;66;03m# preload_content will never buffer chunked responses\u001b[39;00m\n",
      "File \u001b[1;32mc:\\ProgramData\\anaconda3\\Lib\\site-packages\\urllib3\\connectionpool.py:789\u001b[0m, in \u001b[0;36mHTTPConnectionPool.urlopen\u001b[1;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, preload_content, decode_content, **response_kw)\u001b[0m\n\u001b[0;32m    786\u001b[0m response_conn \u001b[38;5;241m=\u001b[39m conn \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m release_conn \u001b[38;5;28;01melse\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[0;32m    788\u001b[0m \u001b[38;5;66;03m# Make the request on the HTTPConnection object\u001b[39;00m\n\u001b[1;32m--> 789\u001b[0m response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_make_request(\n\u001b[0;32m    790\u001b[0m     conn,\n\u001b[0;32m    791\u001b[0m     method,\n\u001b[0;32m    792\u001b[0m     url,\n\u001b[0;32m    793\u001b[0m     timeout\u001b[38;5;241m=\u001b[39mtimeout_obj,\n\u001b[0;32m    794\u001b[0m     body\u001b[38;5;241m=\u001b[39mbody,\n\u001b[0;32m    795\u001b[0m     headers\u001b[38;5;241m=\u001b[39mheaders,\n\u001b[0;32m    796\u001b[0m     chunked\u001b[38;5;241m=\u001b[39mchunked,\n\u001b[0;32m    797\u001b[0m     retries\u001b[38;5;241m=\u001b[39mretries,\n\u001b[0;32m    798\u001b[0m     response_conn\u001b[38;5;241m=\u001b[39mresponse_conn,\n\u001b[0;32m    799\u001b[0m     preload_content\u001b[38;5;241m=\u001b[39mpreload_content,\n\u001b[0;32m    800\u001b[0m     decode_content\u001b[38;5;241m=\u001b[39mdecode_content,\n\u001b[0;32m    801\u001b[0m     \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mresponse_kw,\n\u001b[0;32m    802\u001b[0m )\n\u001b[0;32m    804\u001b[0m \u001b[38;5;66;03m# Everything went great!\u001b[39;00m\n\u001b[0;32m    805\u001b[0m clean_exit \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mTrue\u001b[39;00m\n",
      "File \u001b[1;32mc:\\ProgramData\\anaconda3\\Lib\\site-packages\\urllib3\\connectionpool.py:536\u001b[0m, in \u001b[0;36mHTTPConnectionPool._make_request\u001b[1;34m(self, conn, method, url, body, headers, retries, timeout, chunked, response_conn, preload_content, decode_content, enforce_content_length)\u001b[0m\n\u001b[0;32m    534\u001b[0m \u001b[38;5;66;03m# Receive the response from the server\u001b[39;00m\n\u001b[0;32m    535\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 536\u001b[0m     response \u001b[38;5;241m=\u001b[39m conn\u001b[38;5;241m.\u001b[39mgetresponse()\n\u001b[0;32m    537\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m (BaseSSLError, \u001b[38;5;167;01mOSError\u001b[39;00m) \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[0;32m    538\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_raise_timeout(err\u001b[38;5;241m=\u001b[39me, url\u001b[38;5;241m=\u001b[39murl, timeout_value\u001b[38;5;241m=\u001b[39mread_timeout)\n",
      "File \u001b[1;32mc:\\ProgramData\\anaconda3\\Lib\\site-packages\\urllib3\\connection.py:507\u001b[0m, in \u001b[0;36mHTTPConnection.getresponse\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    504\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mresponse\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m HTTPResponse\n\u001b[0;32m    506\u001b[0m \u001b[38;5;66;03m# Get the response from http.client.HTTPConnection\u001b[39;00m\n\u001b[1;32m--> 507\u001b[0m httplib_response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28msuper\u001b[39m()\u001b[38;5;241m.\u001b[39mgetresponse()\n\u001b[0;32m    509\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m    510\u001b[0m     assert_header_parsing(httplib_response\u001b[38;5;241m.\u001b[39mmsg)\n",
      "File \u001b[1;32mc:\\ProgramData\\anaconda3\\Lib\\http\\client.py:1430\u001b[0m, in \u001b[0;36mHTTPConnection.getresponse\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m   1428\u001b[0m     response\u001b[38;5;241m.\u001b[39mbegin()\n\u001b[0;32m   1429\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mConnectionError\u001b[39;00m:\n\u001b[1;32m-> 1430\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mclose()\n\u001b[0;32m   1431\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m\n\u001b[0;32m   1432\u001b[0m \u001b[38;5;28;01massert\u001b[39;00m response\u001b[38;5;241m.\u001b[39mwill_close \u001b[38;5;241m!=\u001b[39m _UNKNOWN\n",
      "File \u001b[1;32m~\\AppData\\Roaming\\Python\\Python312\\site-packages\\botocore\\awsrequest.py:79\u001b[0m, in \u001b[0;36mAWSConnection.close\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m     76\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_expect_header_set \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mFalse\u001b[39;00m\n\u001b[0;32m     77\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_send_called \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mFalse\u001b[39;00m\n\u001b[1;32m---> 79\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mclose\u001b[39m(\u001b[38;5;28mself\u001b[39m):\n\u001b[0;32m     80\u001b[0m     \u001b[38;5;28msuper\u001b[39m()\u001b[38;5;241m.\u001b[39mclose()\n\u001b[0;32m     81\u001b[0m     \u001b[38;5;66;03m# Reset all of our instance state we were tracking.\u001b[39;00m\n",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "# DB 테이블 생성 확인  \n",
    "from data_engineering.db.init_db import create_object_storage_table  \n",
    "create_object_storage_table()  \n",
    "\n",
    "# 이미 업로드된 파일 목록 가져오기  \n",
    "uploaded_files = get_uploaded_files()  \n",
    "print(f\"이미 업로드된 파일 수: {len(uploaded_files)}\")  \n",
    "\n",
    "# 임시 디렉토리 생성  \n",
    "temp_dir = tempfile.mkdtemp()  \n",
    "print(f\"임시 디렉토리 생성됨: {temp_dir}\")  \n",
    "\n",
    "try:  \n",
    "    # 각 디렉토리 처리  \n",
    "    for dir_path in DIRECTORIES:  \n",
    "        current_path = os.path.join(DATASET_PATH, dir_path)  \n",
    "        print(f\"\\n처리 중인 디렉토리: {dir_path}\")  \n",
    "        \n",
    "        # ZIP 파일 목록 가져오기  \n",
    "        zip_files = [f for f in os.listdir(current_path) if f.endswith('.zip')]  \n",
    "        print(f\"발견된 ZIP 파일 수: {len(zip_files)}\")  \n",
    "        \n",
    "        # 각 ZIP 파일 처리  \n",
    "        for zip_filename in tqdm(zip_files, desc=\"ZIP 파일 처리 중\"):  \n",
    "            zip_path = os.path.join(current_path, zip_filename)  \n",
    "            category = f\"{dir_path}/{os.path.splitext(zip_filename)[0]}\"  \n",
    "            \n",
    "            with zipfile.ZipFile(zip_path, 'r') as zip_ref:  \n",
    "                for file_info in tqdm(zip_ref.filelist, desc=\"파일 추출 중\"):  \n",
    "                    if is_image_file(file_info.filename):  \n",
    "                        object_key = f\"{category}/{os.path.basename(file_info.filename)}\"  \n",
    "                        \n",
    "                        # 이미 업로드된 파일 건너뛰기  \n",
    "                        if (category, object_key) in uploaded_files:  \n",
    "                            continue  \n",
    "                        \n",
    "                        # 임시 파일로 추출  \n",
    "                        temp_path = os.path.join(temp_dir, os.path.basename(file_info.filename))  \n",
    "                        with zip_ref.open(file_info) as source, open(temp_path, 'wb') as target:  \n",
    "                            shutil.copyfileobj(source, target)  \n",
    "                        \n",
    "                        try:  \n",
    "                            # MinIO 업로드 및 메타데이터 저장  \n",
    "                            success = upload_file_with_metadata(  \n",
    "                                local_path=temp_path,  \n",
    "                                category=category,  \n",
    "                                bucket=BUCKET_NAME,  \n",
    "                                object_path=object_key  \n",
    "                            )  \n",
    "                            if not success:  \n",
    "                                print(f\"업로드 실패: {object_key}\")  \n",
    "                        except Exception as e:  \n",
    "                            print(f\"처리 실패: {object_key} - {str(e)}\")  \n",
    "                        \n",
    "                        # 임시 파일 삭제  \n",
    "                        os.remove(temp_path)  \n",
    "\n",
    "finally:  \n",
    "    # 임시 디렉토리 정리  \n",
    "    shutil.rmtree(temp_dir)  \n",
    "    print(\"임시 디렉토리 정리 완료\")  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 최종 상태 확인  \n",
    "db = Database(  \n",
    "    host=os.getenv('DB_HOST'),  \n",
    "    port=int(os.getenv('DB_PORT')),  \n",
    "    user=os.getenv('DB_USER'),  \n",
    "    password=os.getenv('DB_PASSWORD'),  \n",
    "    database=os.getenv('DB_NAME')  \n",
    ")  \n",
    "\n",
    "query = \"SELECT COUNT(*) as count FROM object_storage\"  \n",
    "result = db.getter(query)  \n",
    "print(f\"\\n총 업로드된 파일 수: {result[0]['count']}\")  \n",
    "\n",
    "# 카테고리별 통계 확인  \n",
    "query = \"\"\"  \n",
    "SELECT category, COUNT(*) as count   \n",
    "FROM object_storage   \n",
    "GROUP BY category   \n",
    "ORDER BY count DESC  \n",
    "\"\"\"  \n",
    "records = db.getter(query)  \n",
    "print(\"\\n카테고리별 파일 수:\")  \n",
    "for record in records:  \n",
    "    print(f\"- {record['category']}: {record['count']}개\")  "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
